-- Create jobs table
CREATE TABLE public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT,
  job_type TEXT, -- e.g., 'Full-time', 'Part-time', 'Contract'
  salary_min INT,
  salary_max INT,
  status TEXT DEFAULT 'open' NOT NULL, -- e.g., 'open', 'closed', 'archived'
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add comments to jobs table columns
COMMENT ON COLUMN public.jobs.job_type IS 'e.g., ''Full-time'', ''Part-time'', ''Contract''';
COMMENT ON COLUMN public.jobs.status IS 'e.g., ''open'', ''closed'', ''archived''';

-- Create applications table
CREATE TABLE public.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE NOT NULL,
  talent_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'submitted' NOT NULL, -- e.g., 'submitted', 'viewed', 'accepted', 'rejected'
  cover_letter TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (job_id, talent_id) -- Prevent duplicate applications
);

-- Add comments to applications table columns
COMMENT ON COLUMN public.applications.status IS 'e.g., ''submitted'', ''viewed'', ''accepted'', ''rejected''';
COMMENT ON CONSTRAINT applications_job_id_talent_id_key ON public.applications IS 'Prevent duplicate applications';

-- Enable Row Level Security for both tables
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- RLS Policies for jobs table
CREATE POLICY "Companies can create their own jobs." ON public.jobs
  FOR INSERT WITH CHECK (auth.uid() = company_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'company');

CREATE POLICY "Authenticated users can view open jobs." ON public.jobs
  FOR SELECT USING (status = 'open');

CREATE POLICY "Companies can view their own jobs." ON public.jobs
  FOR SELECT USING (auth.uid() = company_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'company');

CREATE POLICY "Companies can update their own jobs." ON public.jobs
  FOR UPDATE USING (auth.uid() = company_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'company');

-- RLS Policies for applications table
CREATE POLICY "Talents can create applications for open jobs." ON public.applications
  FOR INSERT WITH CHECK (
    auth.uid() = talent_id AND
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'talent' AND
    (SELECT status FROM public.jobs WHERE id = job_id) = 'open'
  );

CREATE POLICY "Talents can view their own applications." ON public.applications
  FOR SELECT USING (auth.uid() = talent_id);

CREATE POLICY "Companies can view applications for their jobs." ON public.applications
  FOR SELECT USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'company' AND
    job_id IN (SELECT id FROM public.jobs WHERE company_id = auth.uid())
  );

CREATE POLICY "Companies can update application status for their jobs." ON public.applications
  FOR UPDATE USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'company' AND
    job_id IN (SELECT id FROM public.jobs WHERE company_id = auth.uid())
  ) WITH CHECK (status IN ('viewed', 'accepted', 'rejected'));
